//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 8/15/2016 10:08:58 PM

#ifndef __emuInvadersResource_h__
#define __emuInvadersResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:emuInvadersResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x45564157 (wave)
#define REF_WAV_BASE_HIT 36
#define REF_WAV_INV_HIT 6589
#define REF_WAV_SHOT 10674
#define REF_WAV_UFO 14056
#define REF_WAV_UFO_HIT 15863
#define REF_WAV_WALK1 41673
#define REF_WAV_WALK2 42711
#define REF_WAV_WALK3 43710
#define REF_WAV_WALK4 44711

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_BACKGROUND 45673

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_DEFAULT 199278

#endif

